/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package almaquerubina;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author crist
 */
public class Cita extends javax.swing.JFrame {
    public CitaTableModel citaTModel = new CitaTableModel(); 
   SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");//Formato de fecha del jdatechooser
    private Connection conexion;

    /**
     * Creates new form Cita
     */
    public Cita() {
        initComponents();
        
        this.setLocationRelativeTo(Cita.this);
         Image ico = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconos/diente1.png"));
   this.setIconImage(ico);
   Cita.super.setTitle("BUSCAR CITA");
   inicializarColumnas();
   Cita.super.setLocationRelativeTo(Cita.this);
   Cita.super.setSize(1150,600);
   conectar();
   consultaInicial();
   
    }
    private void consultaInicial() {
try { 
String sentenciaSql = "select codigo_paciente,nombre,telefono,fecha from cita  natural join paciente ";
java.sql.Statement statement = this.conexion.createStatement();
ResultSet resultado = statement.executeQuery(sentenciaSql);
while (resultado.next()) {
Citas cita = new Citas();
cita.codigo = resultado.getString("codigo_paciente");
cita.paciente = resultado.getString("nombre");
cita.tel=resultado.getString("telefono");
cita.fecha=resultado.getString("fecha");

this.citaTModel.citas.add(cita);
}
TableCitas.repaint();
} catch (SQLException ex) {
JOptionPane.showMessageDialog(this, "Error al recuperar los productos de la base de datos");
ex.printStackTrace();
}
}
    private void conectar() {
try {
conexion = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Clinica", "ZT12002",
"prn315ZT12002");
} catch (SQLException ex) {
Logger.getLogger(Cita.class.getName()).log(Level.SEVERE, null, ex);
}
}
    private void inicializarColumnas() {
TableColumnModel tColumnModel = new DefaultTableColumnModel();
for (int i = 0; i < 4; i++) {
TableColumn col = new TableColumn(i);
switch (i) {
case 0:
col.setHeaderValue("Código");
break;
case 1:
col.setHeaderValue("Nombre");
break;
case 2:
col.setHeaderValue("Telefono");
break;
case 3:
col.setHeaderValue("Fecha");
}
tColumnModel.addColumn(col);
}
TableCitas.setColumnModel(tColumnModel);
}
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableCitas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fechas = new com.toedter.calendar.JCalendar();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TableCitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TableCitas.setModel(citaTModel);
        jScrollPane1.setViewportView(TableCitas);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/almaquerubina/icon/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/almaquerubina/icon/find.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo de Paciente:");

        jLabel2.setText("Buscar");

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fechas, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(253, 253, 253))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(152, 152, 152))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cerrar();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        citaTModel.citas.clear();
        String fechaObtenida = sdf.format(fechas.getDate());
       
try {
    if(txtcodigo.getText().isEmpty()){
        
    
PreparedStatement statement = null;
String fecha = fechas.getDate().toString();
String sentenciaSql = "select * from cita  natural join paciente where fecha= " ;
    sentenciaSql+="?";

    statement = this.conexion.prepareStatement(sentenciaSql);
statement.setString(1, fechaObtenida );


ResultSet resultado = statement.executeQuery();
while (resultado.next()) {
Citas cita = new Citas();
cita.codigo = resultado.getString("codigo_paciente");
cita.paciente = resultado.getString("nombre");
cita.tel=resultado.getString("telefono");
cita.tel2=resultado.getString("telefono_2");
cita.fecha=resultado.getString("fecha");
this.citaTModel.citas.add(cita);
}
    }
    else{
     PreparedStatement statement = null;

String sentenciaSql = "select * from cita  natural join paciente  " ;
    sentenciaSql+="where codigo_paciente=? ";

    statement = this.conexion.prepareStatement(sentenciaSql);
statement.setString(1, txtcodigo.getText() );
ResultSet resultado = statement.executeQuery();
while (resultado.next()) {
Citas cita = new Citas();
cita.codigo = resultado.getString("codigo_paciente");
cita.paciente = resultado.getString("nombre");
cita.tel=resultado.getString("telefono");
cita.fecha=resultado.getString("fecha");
this.citaTModel.citas.add(cita);
}   
    }
TableCitas.repaint();
} catch (SQLException ex) {
JOptionPane.showMessageDialog(this, "Error al recuperar los productos de la base de datos");
ex.printStackTrace();


}        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int column = 4;
int row = TableCitas.getSelectedRow();
String indice = TableCitas.getModel().getValueAt(row, column).toString();
        
        try{
            PreparedStatement statement = null;

String sentenciaSql = "delete from cita " ;
    sentenciaSql+="where fecha = ?";
    
    PreparedStatement preparedStatement = conexion.prepareStatement(sentenciaSql);
    preparedStatement.setString(1, indice);
    
    preparedStatement.execute();
    JOptionPane.showMessageDialog(rootPane, "cita eliminado exitosamente");
    UpdateJTable();
        } catch (SQLException ex) {
        Logger.getLogger(Pacientes.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(rootPane, "Error al borrar la cita");
    }
        
    }//GEN-LAST:event_jButton3ActionPerformed
private void UpdateJTable() {
citaTModel.citas.clear();
try {
PreparedStatement statement = null;
String sentenciaSql = "select * from cita  natural join paciente";
statement = this.conexion.prepareStatement(sentenciaSql);
ResultSet resultado = statement.executeQuery();
while (resultado.next()) {
Citas cita = new Citas();
cita.codigo = resultado.getString("codigo_paciente");
cita.paciente = resultado.getString("nombre");
cita.tel=resultado.getString("telefono");
cita.fecha=resultado.getString("fecha");
citaTModel.citas.add(cita);
}
TableCitas.repaint();
} catch (SQLException ex) {
JOptionPane.showMessageDialog(this, "Error al recuperar las citas de la base de datos");
ex.printStackTrace();
}
}
    /**
     * @param args the command line arguments
     */
     public void cerrar(){
    WindowEvent WinClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WinClosingEvent);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCitas;
    private com.toedter.calendar.JCalendar fechas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables
}
